// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the player reports when you start watching something.
 */
export type ActivityInput = { metaId: string, contentType: string, title: string, subtitle: string, poster: string | null, 
/**
 * ISO-8601 timestamp from the client, so the feed orders correctly.
 */
updatedAt: string, };
