// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An addon that was asked for something and didn't deliver. Dropping these
 * silently is why "no streams" and "your addon is down" used to look the same.
 */
export type AddonFailure = { addonName: string, message: string, };
