// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend needs to render the auth state.
 */
export type AuthStatus = { signedIn: boolean, email: string | null, 
/**
 * Sign-up succeeded but the address must be confirmed before sign-in.
 */
needsConfirmation: boolean, };
