// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraProp } from "./ExtraProp";

/**
 * One catalog from one installed addon, as shown on the discover board.
 */
export type CatalogDescriptor = { transportUrl: string, addonName: string, type: string, id: string, name: string | null, extra: Array<ExtraProp>, };
