// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the download cache, as shown on the downloads page.
 */
export type DownloadEntry = { name: string, sizeBytes: bigint, };
