// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtraProp = { name: string, isRequired: boolean, options: Array<string>, optionsLimit: number | null, };
