// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the activity feed — what a friend is watching. Empty from
 * the local backend; a server fills this in.
 */
export type FriendActivity = { friendId: string, friendName: string, avatarColor: string, 
/**
 * The thing being watched ("Breaking Bad").
 */
title: string, 
/**
 * The line under it ("S1 · E3", or "Watching now").
 */
subtitle: string, poster: string | null, metaId: string, contentType: string, atMs: bigint, };
