// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Friend = { id: string, displayName: string, avatar: string, avatarColor: string, friendCode: string, };
