// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the activity feed — what a friend is watching.
 */
export type FriendActivity = { friendId: string, friendName: string, avatar: string, avatarColor: string, 
/**
 * The thing being watched ("Breaking Bad").
 */
title: string, 
/**
 * The line under it ("S1 · E3", or "Watching now").
 */
subtitle: string, poster: string | null, metaId: string, contentType: string, 
/**
 * ISO-8601 timestamp of when they last updated it; the UI turns this
 * into a relative "2h ago".
 */
updatedAt: string, };
