// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the user explicitly saved to their library.
 */
export type LibraryItem = { metaId: string, type: string, name: string, poster: string | null, addedAtMs: bigint, };
