// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraProp } from "./ExtraProp";

/**
 * A catalog entry announced in the manifest.
 */
export type ManifestCatalog = { id: string, type: string, name: string | null, 
/**
 * Extra query properties the catalog supports (search, genre, skip, ...).
 */
extra: Array<ExtraProp>, };
