// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestBehaviorHints } from "./ManifestBehaviorHints";
import type { ManifestCatalog } from "./ManifestCatalog";
import type { ResourceRef } from "./ResourceRef";

/**
 * An addon's self-description, served at `/manifest.json`.
 */
export type Manifest = { id: string, version: string, name: string, description: string | null, 
/**
 * Content types the addon serves ("movie", "series", "channel", "tv", ...).
 */
types: Array<string>, resources: Array<ResourceRef>, catalogs: Array<ManifestCatalog>, 
/**
 * Meta id prefixes the addon responds to (e.g. "tt" for IMDb ids).
 */
idPrefixes: Array<string> | null, background: string | null, logo: string | null, contactEmail: string | null, behaviorHints: ManifestBehaviorHints, };
