// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight meta item as returned inside catalogs.
 */
export type MetaPreview = { id: string, type: string, name: string, poster: string | null, 
/**
 * "poster" (portrait), "landscape" or "square"; left as a string since
 * addons in the wild put arbitrary values here.
 */
posterShape: string | null, background: string | null, logo: string | null, description: string | null, releaseInfo: string | null, imdbRating: string | null, genres: Array<string>, };
