// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaBehaviorHints } from "./MetaBehaviorHints";
import type { Video } from "./Video";

/**
 * The full meta object served by a `/meta/...` resource.
 */
export type MetaDetail = { id: string, type: string, name: string, poster: string | null, posterShape: string | null, background: string | null, logo: string | null, description: string | null, releaseInfo: string | null, released: string | null, runtime: string | null, imdbRating: string | null, genres: Array<string>, cast: Array<string>, director: Array<string>, writer: Array<string>, website: string | null, 
/**
 * Episodes/videos for series; empty for movies.
 */
videos: Array<Video>, behaviorHints: MetaBehaviorHints, };
