// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in user's identity, as the server holds it.
 */
export type Profile = { 
/**
 * The account id (same as the auth user's).
 */
id: string, displayName: string, 
/**
 * Short code others use to add this profile as a friend.
 */
friendCode: string, 
/**
 * Avatar tint (hex). An uploaded image can come later.
 */
avatarColor: string, 
/**
 * False until they've picked a name and avatar; the app shows the
 * setup screen instead of the board while it is.
 */
onboarded: boolean, };
