// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The local user's identity.
 */
export type Profile = { 
/**
 * Stable id. Empty until provisioned on first run; becomes the account
 * id once a server exists.
 */
id: string, displayName: string, 
/**
 * Short code others use to add this profile as a friend.
 */
friendCode: string, 
/**
 * Avatar tint (hex). An uploaded image can come later.
 */
avatarColor: string, };
