// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editable slice of a profile; identity fields stay server/owned.
 */
export type ProfileUpdate = { displayName: string, avatar: string, avatarColor: string, };
