// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fields the frontend reports while playing; the timestamp is added here.
 */
export type ProgressUpdate = { metaId: string, videoId: string, type: string, name: string, poster: string | null, positionSecs: number, durationSecs: number, };
