// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The resolution tiers people actually choose between.
 */
export type Quality = "uhd" | "fhd" | "hd" | "sd";
