// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamBehaviorHints } from "./StreamBehaviorHints";
import type { StreamFacts } from "./StreamFacts";
import type { Subtitle } from "./Subtitle";

/**
 * A stream with what we managed to read off its release name.
 */
export type RankedStream = { facts: StreamFacts, 
/**
 * Whether the player you're actually using can decode this. mpv can
 * decode anything, so this only ever goes false on the webview.
 */
playable: boolean, addonName: string, 
/**
 * Short label, usually the addon or quality name.
 */
name: string | null, 
/**
 * Older addons put the description in "title".
 */
title: string | null, description: string | null, subtitles: Array<Subtitle>, behaviorHints: StreamBehaviorHints, } & ({ url: string, } | { ytId: string, } | { infoHash: string, fileIdx: number | null, 
/**
 * Extra trackers/DHT sources, e.g. "tracker:udp://..." or "dht:...".
 */
sources: Array<string>, } | { externalUrl: string, });
