// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource the addon provides. The protocol allows either a bare name
 * ("stream") or an object that scopes it to certain types/id prefixes.
 */
export type ResourceRef = string | { name: string, types: Array<string> | null, idPrefixes: Array<string> | null, };
