// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the player ends up with after a stream source is resolved.
 */
export type ResolvedStream = { 
/**
 * Directly playable URL (remote for http streams, local for torrents).
 */
playUrl: string, fileName: string | null, };
