// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User preferences. `default` on the container keeps old settings files
 * working when new fields appear.
 */
export type Settings = { 
/**
 * Accent preset id; the frontend maps it to concrete colors.
 */
accent: string, 
/**
 * Prefer the embedded mpv over the webview <video> element.
 */
useMpv: boolean, 
/**
 * mpv hwdec: auto-safe when on, software decoding when off.
 */
hardwareDecoding: boolean, 
/**
 * mpv sub-scale multiplier.
 */
subtitleScale: number, 
/**
 * Torrent download cap in MB/s; 0 means unlimited.
 */
downloadLimitMbps: number, 
/**
 * Torrent upload cap in MB/s; 0 means unlimited.
 */
uploadLimitMbps: number, };
