// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipKind } from "./SkipKind";

/**
 * A stretch of an episode worth offering to skip.
 */
export type SkipSegment = { kind: SkipKind, startSecs: number, endSecs: number, };
