// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quality } from "./Quality";
import type { RankedStream } from "./RankedStream";

/**
 * One quality's worth of streams: the one we'd press play on, and the rest
 * kept behind it for anyone who wants to look.
 */
export type StreamTier = { quality: Quality, label: string, 
/**
 * The tier a single press of play would open — the quality asked for in
 * settings, or the best available when it isn't served.
 */
preferred: boolean, best: RankedStream, alternatives: Array<RankedStream>, };
