// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the stream actually comes from. Exactly one of these shapes is
 * present in the JSON; `untagged` picks the first that fits.
 */
export type StreamSource = { url: string, } | { ytId: string, } | { infoHash: string, fileIdx: number | null, 
/**
 * Extra trackers/DHT sources, e.g. "tracker:udp://..." or "dht:...".
 */
sources: Array<string>, } | { externalUrl: string, };
