// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamBehaviorHints } from "./StreamBehaviorHints";
import type { Subtitle } from "./Subtitle";

/**
 * One playable option for a video, as served by a `/stream/...` resource.
 */
export type Stream = { 
/**
 * Short label, usually the addon or quality name.
 */
name: string | null, 
/**
 * Older addons put the description in "title".
 */
title: string | null, description: string | null, subtitles: Array<Subtitle>, behaviorHints: StreamBehaviorHints, } & ({ url: string, } | { ytId: string, } | { infoHash: string, fileIdx: number | null, 
/**
 * Extra trackers/DHT sources, e.g. "tracker:udp://..." or "dht:...".
 */
sources: Array<string>, } | { externalUrl: string, });
