// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Quality } from "./Quality";

/**
 * What the release name gave up.
 */
export type StreamFacts = { quality: Quality, 
/**
 * HDR10, HDR10+, Dolby Vision — anything that needs a capable player.
 */
hdr: boolean, 
/**
 * HEVC/AV1 and MKV don't play in the webview yet; H.264 in MP4 does.
 */
webPlayable: boolean, seeders: number | null, sizeBytes: bigint | null, 
/**
 * What the release calls itself, minus the addon's own decoration.
 */
release: string | null, 
/**
 * Where the video came from: WEB-DL, BluRay, HDTV…
 */
source: string | null, 
/**
 * H.264, H.265, AV1, XviD.
 */
codec: string | null, 
/**
 * Atmos, DTS-HD, DDP 5.1 — only the ones worth mentioning.
 */
audio: string | null, };
