// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamBehaviorHints = { 
/**
 * True when the webview `<video>` element likely can't play this
 * directly (codec/container not browser-friendly).
 */
notWebReady: boolean, 
/**
 * Streams sharing a binge group continue with the same quality/addon
 * when the next episode starts.
 */
bingeGroup: string | null, countryWhitelist: Array<string> | null, filename: string | null, videoSize: bigint | null, };
