// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonFailure } from "./AddonFailure";
import type { StreamTier } from "./StreamTier";

/**
 * Streams, grouped into qualities, plus whoever failed to answer.
 */
export type StreamsView = { tiers: Array<StreamTier>, failures: Array<AddonFailure>, };
