// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A subtitle track offered by an addon or attached to a stream.
 */
export type Subtitle = { id: string | null, url: string, 
/**
 * ISO 639 language code, though addons don't always stick to it.
 */
lang: string, };
