// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a torrent is doing right now, so the player can say something more
 * useful than "loading" while it waits for the first pieces.
 */
export type TorrentProgress = { 
/**
 * Still resolving the magnet — no metadata, no peers, nothing to show.
 */
initializing: boolean, peers: number, downloadMbps: number, downloadedBytes: bigint, totalBytes: bigint, };
