// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stream } from "./Stream";

export type Video = { id: string, 
/**
 * Cinemeta uses "name", the spec says "title" — accept both.
 */
title: string | null, released: string | null, thumbnail: string | null, season: number | null, episode: number | null, overview: string | null, 
/**
 * Some addons embed streams directly in the video object.
 */
streams: Array<Stream> | null, };
