// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the frontend knows when toggling a library item; the timestamp is
 * added here.
 */
export type WatchlistToggle = { metaId: string, type: string, name: string, poster: string | null, };
