// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far someone got into one video, plus enough display data to render
 * a continue-watching card without re-fetching meta.
 */
export type WatchProgress = { 
/**
 * The meta item ("tt0903747"). One entry per meta is kept.
 */
metaId: string, 
/**
 * The concrete video ("tt0903747:1:3"; same as meta_id for movies).
 */
videoId: string, type: string, name: string, poster: string | null, 
/**
 * Landscape artwork for the card. Portrait posters crop badly into a
 * wide frame, so a backdrop is preferred when the addon provides one.
 */
background: string | null, positionSecs: number, durationSecs: number, updatedAtMs: bigint, };
